version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    working_dir: /usr/src/app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s docker-entrypoint.sh node src/app.js
    tty: true
    volumes:
      - ./node:/usr/src/app
    ports:
      - "3000:3000"
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
