version: '3'

services:
  app:
    build:
      context: ./node
    container_name: app
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node src/app.js
    tty: true
    volumes:
      - ./node:/usr/app
      - /usr/app/node_modules
    expose:
      - 3000
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mysql:8.0.28
    container_name: db
    command: --innodb-use-native-aio=0
    restart: always
    tty: true
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=nodedb
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - app-network

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    ports:
      - "8080:80"
    networks:
      - app-network

networks:
  app-network:
    driver: "bridge"
